# Numpy

Numpy is a library which provides support for large, homogeneous, multi-dimensional arrays and matrices. 

In [1]:
# importing numpy library
import numpy as np

# Creating Arrays in Numpy

### Creating an array from a list

In [2]:
list1 = [10,20,30]
list1

[10, 20, 30]

In [3]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [4]:
type(arr1)

numpy.ndarray

### Using arange to create an array

The difference between array and arrange is thaat array takes in a list and turns it into an array, whereas arange creates an array from a range of numbers.

In [6]:
arr2 = np.arange(10,20,1) # (Start, Stop, Step-Size)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Multi-dimensional arrays

### Combining two list - Two-dimensional arrays

When we combine arrays together, we can add dimensions. Combining two arrays gives us a 2D array.

This creates a matrix for us which we can perform matrix operations.

In [7]:
# Let's create a new list to join onto the first list
list2 = [40,50,60]

# Join the lists
list3 = [list1, list2]

# Create an array out of the joined lists
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [9]:
arr3.shape

(2, 3)

### Three-dimensional arrays